"""initial domain schema

Revision ID: 024a5fed003d
Revises:
Create Date: 2026-06-12 07:44:46.257223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '024a5fed003d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demand_clusters',
    sa.Column('canonical_thesis', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('cluster_size', sa.Integer(), nullable=False),
    sa.Column('aggregate_intended_exposure', sa.String(length=32), nullable=True),
    sa.Column('latest_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_snapshots',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('venue_id', sa.String(length=64), nullable=False),
    sa.Column('as_of_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retrieval_id', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_candidates',
    sa.Column('object_type', sa.String(length=32), nullable=False),
    sa.Column('object_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_signals',
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_actor', sa.String(length=256), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('api_clients',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('client_type', sa.String(length=16), nullable=False),
    sa.Column('rate_limit_tier', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_table('attestation_events',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('object_type', sa.String(length=32), nullable=False),
    sa.Column('object_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_rules_captures',
    sa.Column('market_id', sa.String(length=128), nullable=False),
    sa.Column('snapshot_id', sa.String(length=128), nullable=False),
    sa.Column('contract_terms_text', sa.Text(), nullable=False),
    sa.Column('resolution_rules_text', sa.Text(), nullable=False),
    sa.Column('contract_terms_hash', sa.String(length=64), nullable=False),
    sa.Column('resolution_rules_hash', sa.String(length=64), nullable=False),
    sa.Column('rules_captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['market_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market_id', 'snapshot_id', name='uq_rules_capture')
    )
    op.create_table('market_structures',
    sa.Column('market_id', sa.String(length=128), nullable=False),
    sa.Column('snapshot_id', sa.String(length=128), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('structure', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('extraction_policy_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['market_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market_id', 'snapshot_id', 'schema_version', name='uq_market_structure')
    )
    op.create_table('thesis_analyses',
    sa.Column('source_signal_id', sa.Uuid(), nullable=True),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('extracted_structure', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('normalized_claim_summary', sa.Text(), nullable=False),
    sa.Column('client_type', sa.String(length=16), nullable=False),
    sa.Column('agent_client_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_signal_id'], ['source_signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_sets',
    sa.Column('thesis_analysis_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_id', sa.String(length=128), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['market_snapshots.id'], ),
    sa.ForeignKeyConstraint(['thesis_analysis_id'], ['thesis_analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('draft_contracts',
    sa.Column('thesis_analysis_id', sa.Uuid(), nullable=False),
    sa.Column('ledger_entry_id', sa.Uuid(), nullable=True),
    sa.Column('proposed_title', sa.String(length=512), nullable=False),
    sa.Column('proposed_resolution_logic', sa.Text(), nullable=False),
    sa.Column('resolution_source', sa.String(length=256), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('time_horizon', sa.String(length=64), nullable=True),
    sa.Column('cluster_id', sa.Uuid(), nullable=True),
    sa.Column('saved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['demand_clusters.id'], ),
    sa.ForeignKeyConstraint(['thesis_analysis_id'], ['thesis_analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_recommendations',
    sa.Column('thesis_analysis_id', sa.Uuid(), nullable=False),
    sa.Column('recommended_market_id', sa.String(length=128), nullable=True),
    sa.Column('expression_type', sa.String(length=32), nullable=False),
    sa.Column('fit_score', sa.Float(), nullable=False),
    sa.Column('fit_reason', sa.Text(), nullable=False),
    sa.Column('why_now', sa.Text(), nullable=True),
    sa.Column('crowding_note', sa.Text(), nullable=True),
    sa.Column('as_of_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('snapshot_id', sa.String(length=128), nullable=False),
    sa.Column('retrieval_id', sa.String(length=128), nullable=False),
    sa.Column('venue_id', sa.String(length=64), nullable=False),
    sa.Column('contract_terms_hash', sa.String(length=64), nullable=True),
    sa.Column('resolution_rules_hash', sa.String(length=64), nullable=True),
    sa.Column('rules_captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provenance', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['market_snapshots.id'], ),
    sa.ForeignKeyConstraint(['thesis_analysis_id'], ['thesis_analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('odds_locks',
    sa.Column('thesis_analysis_id', sa.Uuid(), nullable=False),
    sa.Column('client_ref', sa.String(length=160), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['thesis_analysis_id'], ['thesis_analyses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thesis_analysis_id', 'client_ref', name='uq_odds_lock')
    )
    op.create_table('candidate_set_members',
    sa.Column('candidate_set_id', sa.Uuid(), nullable=False),
    sa.Column('market_id', sa.String(length=128), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('retrieval_score', sa.Float(), nullable=True),
    sa.Column('eligibility_flags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('excluded_reason', sa.String(length=256), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_set_id'], ['candidate_sets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_set_id', 'market_id', name='uq_candidate_member')
    )
    op.create_table('fit_cards',
    sa.Column('thesis_analysis_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_set_id', sa.Uuid(), nullable=False),
    sa.Column('semantic_fit_class', sa.String(length=32), nullable=False),
    sa.Column('recommended_market_id', sa.String(length=128), nullable=True),
    sa.Column('what_it_captures', sa.Text(), nullable=False),
    sa.Column('what_it_misses', sa.Text(), nullable=False),
    sa.Column('horizon_match', sa.String(length=8), nullable=False),
    sa.Column('resolution_risk', sa.String(length=8), nullable=False),
    sa.Column('fit_confidence', sa.Float(), nullable=False),
    sa.Column('draft_contract_id', sa.Uuid(), nullable=True),
    sa.Column('provenance', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_set_id'], ['candidate_sets.id'], ),
    sa.ForeignKeyConstraint(['draft_contract_id'], ['draft_contracts.id'], ),
    sa.ForeignKeyConstraint(['thesis_analysis_id'], ['thesis_analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rejected_markets',
    sa.Column('market_recommendation_id', sa.Uuid(), nullable=False),
    sa.Column('market_id', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['market_recommendation_id'], ['market_recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ledger_entries',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('thesis_analysis_id', sa.Uuid(), nullable=False),
    sa.Column('thesis_summary', sa.Text(), nullable=False),
    sa.Column('user_justification', sa.Text(), nullable=False),
    sa.Column('linked_market_id', sa.String(length=128), nullable=True),
    sa.Column('odds_at_entry', sa.Float(), nullable=True),
    sa.Column('snapshot_id', sa.String(length=128), nullable=True),
    sa.Column('fit_class', sa.String(length=32), nullable=False),
    sa.Column('fit_card_id', sa.Uuid(), nullable=False),
    sa.Column('attestation_status', sa.String(length=16), nullable=False),
    sa.Column('client_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fit_card_id'], ['fit_cards.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['market_snapshots.id'], ),
    sa.ForeignKeyConstraint(['thesis_analysis_id'], ['thesis_analyses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conviction_events',
    sa.Column('thesis_analysis_id', sa.Uuid(), nullable=False),
    sa.Column('ledger_entry_id', sa.Uuid(), nullable=True),
    sa.Column('conviction_level', sa.String(length=16), nullable=True),
    sa.Column('intended_exposure_bucket', sa.String(length=8), nullable=True),
    sa.Column('prior_probability', sa.Float(), nullable=True),
    sa.Column('prior_confidence', sa.String(length=8), nullable=True),
    sa.Column('prior_reason', sa.Text(), nullable=True),
    sa.Column('prior_type', sa.String(length=8), nullable=False),
    sa.Column('market_context_seen', sa.Boolean(), nullable=False),
    sa.Column('prior_recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('odds_revealed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('client_type', sa.String(length=16), nullable=False),
    sa.Column('agent_client_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ledger_entry_id'], ['ledger_entries.id'], ),
    sa.ForeignKeyConstraint(['thesis_analysis_id'], ['thesis_analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conviction_events')
    op.drop_table('ledger_entries')
    op.drop_table('rejected_markets')
    op.drop_table('fit_cards')
    op.drop_table('candidate_set_members')
    op.drop_table('odds_locks')
    op.drop_table('market_recommendations')
    op.drop_table('draft_contracts')
    op.drop_table('candidate_sets')
    op.drop_table('thesis_analyses')
    op.drop_table('market_structures')
    op.drop_table('market_rules_captures')
    op.drop_table('attestation_events')
    op.drop_table('api_clients')
    op.drop_table('users')
    op.drop_table('source_signals')
    op.drop_table('review_candidates')
    op.drop_table('market_snapshots')
    op.drop_table('demand_clusters')
    # ### end Alembic commands ###
